export const articles = [
    {
        id: "1",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 1",
    },
    {
        id: "2",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 2",
    },
    {
        id: "3",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 3",
    },
    {
        id: "4",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 4",
    },
    {
        id: "5",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 5",
    },
    {
        id: "6",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 6",
    },
    {
        id: "7",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 7",
    },
    {
        id: "8",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 8",
    },
    {
        id: "9",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 9",
    },
    {
        id: "10",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 10",
    },
    {
        id: "11",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 11",
    },
    {
        id: "12",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 12",
    },
    {
        id: "13",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 13",
    },
    {
        id: "14",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 14",
    },
    {
        id: "15",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 15",
    },
    {
        id: "16",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 16",
    },
    {
        id: "17",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 17",
    },
    {
        id: "18",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 18",
    },
    {
        id: "19",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 19",
    },
    {
        id: "20",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 20",
    },
    {
        id: "21",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 21",
    },
    {
        id: "22",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 22",
    },
    {
        id: "23",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 23",
    },
    {
        id: "24",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 24",
    },
    {
        id: "25",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 25",
    },
    {
        id: "26",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 26",
    },
    {
        id: "27",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 27",
    },
    {
        id: "28",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 28",
    },
    {
        id: "29",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 29",
    },
    {
        id: "30",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 30",
    },
    {
        id: "31",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 31",
    },
    {
        id: "32",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 32",
    },
    {
        id: "33",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 33",
    },
    {
        id: "34",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 34",
    },
    {
        id: "35",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 35",
    },
    {
        id: "36",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 36",
    },
    {
        id: "37",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 37",
    },
    {
        id: "38",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 38",
    },
    {
        id: "39",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 39",
    },
    {
        id: "40",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 40",
    },
    {
        id: "41",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 41",
    },
    {
        id: "42",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 42",
    },
    {
        id: "43",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 43",
    },
    {
        id: "44",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 44",
    },
    {
        id: "45",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 45",
    },
    {
        id: "46",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 46",
    },
    {
        id: "47",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 47",
    },
    {
        id: "48",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 48",
    },
    {
        id: "49",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 49",
    },
    {
        id: "50",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 50",
    },
    {
        id: "51",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 51",
    },
    {
        id: "52",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 52",
    },
    {
        id: "53",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 53",
    },
    {
        id: "54",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 54",
    },
    {
        id: "55",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 55",
    },
    {
        id: "56",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 56",
    },
    {
        id: "57",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 57",
    },
    {
        id: "58",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 58",
    },
    {
        id: "59",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 59",
    },
    {
        id: "60",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 60",
    },
    {
        id: "61",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 61",
    },
    {
        id: "62",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 62",
    },
    {
        id: "63",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 63",
    },
    {
        id: "64",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 64",
    },
    {
        id: "65",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 65",
    },
    {
        id: "66",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 66",
    },
    {
        id: "67",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 67",
    },
    {
        id: "68",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 68",
    },
    {
        id: "69",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 69",
    },
    {
        id: "70",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 70",
    },
    {
        id: "71",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 71",
    },
    {
        id: "72",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 72",
    },
    {
        id: "73",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 73",
    },
    {
        id: "74",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 74",
    },
    {
        id: "75",
        approved: false,
        authorId: "1",
        content: "placeholder",
        title: "My Title 75",
    },
];
